[workspace]
resolver = "3"
members = ["info", "user_input", "digkult-kozep-2025-tavasz", "digkult-kozep-2024-osz", "digkult-kozep-2024-tavasz", "digkult-kozep-2023-osz", "digkult-kozep-2023-tavasz", "digkult-emelt-2025-tavasz", "inf-emelt-2014-osz"]
